[project]
name = "data-warehouse"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.37.1",
    "botocore>=1.37.1",
    "redis>=5.2.1",
]
